# Makefile.in generated by automake 1.15 from Makefile.am.
# src/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# GLIB - Library of useful C routines





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/aravis
pkgincludedir = $(includedir)/aravis
pkglibdir = $(libdir)/aravis
pkglibexecdir = $(libexecdir)/aravis
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = armv7l-unknown-linux-gnueabihf
host_triplet = armv7l-unknown-linux-gnueabihf
#am__append_1 = \
#	arvuvinterface.c			\
#	arvuvdevice.c				\
#	arvuvstream.c

#am__append_2 = \
#	arvuvcp.c				\
#	arvuvsp.c

#am__append_3 = \
#	arvuvinterface.h			\
#	arvuvdevice.h				\
#	arvuvstream.h

#am__append_4 = \
#	arvuvcp.h				\
#	arvuvsp.h

bin_PROGRAMS = arv-fake-gv-camera-0.6$(EXEEXT) \
	arv-tool-0.6$(EXEEXT) \
	arv-test-0.6$(EXEEXT)
am__append_5 = Aravis-0.6.gir
am__append_6 = $(gir_DATA) $(typelib_DATA)
subdir = src
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/appstream-xml.m4 \
	$(top_srcdir)/m4/ax_code_coverage.m4 \
	$(top_srcdir)/m4/ax_valgrind_check.m4 \
	$(top_srcdir)/m4/glib-gettext.m4 $(top_srcdir)/m4/gtk-doc.m4 \
	$(top_srcdir)/m4/intltool.m4 $(top_srcdir)/m4/introspection.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/m4/nls.m4 \
	$(top_srcdir)/m4/pkg.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am \
	$(am__libaravis_0.6_la_HEADERS_DIST) \
	$(noinst_HEADERS) $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = arvconfig.h
CONFIG_CLEAN_FILES = arvfeatures.h arvversion.h
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(arv_fake_cameradir)" "$(DESTDIR)$(girdir)" \
	"$(DESTDIR)$(typelibdir)" \
	"$(DESTDIR)$(libaravis_0.6_ladir)" \
	"$(DESTDIR)$(libaravis_0.6_ladir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
am__DEPENDENCIES_1 =
libaravis_0.6_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
am__libaravis_0.6_la_SOURCES_DIST = arvenums.c \
	arvdebug.c arvsystem.c arvevaluator.c arvdomnode.c \
	arvdomnodelist.c arvdomnamednodemap.c arvdomdocument.c \
	arvdomdocumentfragment.c arvdomelement.c arvdomcharacterdata.c \
	arvdomtext.c arvdomparser.c arvdomimplementation.c arvcamera.c \
	arvgc.c arvgcnode.c arvgcpropertynode.c arvgcindexnode.c \
	arvgcvalueindexednode.c arvgcinvalidatornode.c \
	arvgcfeaturenode.c arvgcregisterdescriptionnode.c \
	arvgcgroupnode.c arvgccategory.c arvgcboolean.c \
	arvgcenumeration.c arvgcenumentry.c arvgcintegernode.c \
	arvgcfloatnode.c arvgcregisternode.c arvgcstructentrynode.c \
	arvgccommand.c arvgcswissknife.c arvgcconverter.c arvgcport.c \
	arvgcregister.c arvgcinteger.c arvgcstring.c arvgcfloat.c \
	arvinterface.c arvdevice.c arvstream.c arvbuffer.c \
	arvchunkparser.c arvgvinterface.c arvgvdevice.c arvgvstream.c \
	arvfakeinterface.c arvfakedevice.c arvfakestream.c \
	arvfakecamera.c arvgvfakecamera.c arvrealtime.c arvxmlschema.c \
	arvuvinterface.c arvuvdevice.c arvuvstream.c arvmisc.c \
	arvzip.c arvstr.c arvgvcp.c arvgvsp.c arvuvcp.c arvuvsp.c \
	arvenumtypes.c
#am__objects_1 = arvuvinterface.lo \
#	arvuvdevice.lo arvuvstream.lo
am__objects_2 = arvenums.lo arvdebug.lo arvsystem.lo arvevaluator.lo \
	arvdomnode.lo arvdomnodelist.lo arvdomnamednodemap.lo \
	arvdomdocument.lo arvdomdocumentfragment.lo arvdomelement.lo \
	arvdomcharacterdata.lo arvdomtext.lo arvdomparser.lo \
	arvdomimplementation.lo arvcamera.lo arvgc.lo arvgcnode.lo \
	arvgcpropertynode.lo arvgcindexnode.lo \
	arvgcvalueindexednode.lo arvgcinvalidatornode.lo \
	arvgcfeaturenode.lo arvgcregisterdescriptionnode.lo \
	arvgcgroupnode.lo arvgccategory.lo arvgcboolean.lo \
	arvgcenumeration.lo arvgcenumentry.lo arvgcintegernode.lo \
	arvgcfloatnode.lo arvgcregisternode.lo arvgcstructentrynode.lo \
	arvgccommand.lo arvgcswissknife.lo arvgcconverter.lo \
	arvgcport.lo arvgcregister.lo arvgcinteger.lo arvgcstring.lo \
	arvgcfloat.lo arvinterface.lo arvdevice.lo arvstream.lo \
	arvbuffer.lo arvchunkparser.lo arvgvinterface.lo \
	arvgvdevice.lo arvgvstream.lo arvfakeinterface.lo \
	arvfakedevice.lo arvfakestream.lo arvfakecamera.lo \
	arvgvfakecamera.lo arvrealtime.lo arvxmlschema.lo \
	$(am__objects_1)
#am__objects_3 = arvuvcp.lo arvuvsp.lo
am__objects_4 = arvmisc.lo arvzip.lo arvstr.lo arvgvcp.lo arvgvsp.lo \
	$(am__objects_3)
am_libaravis_0.6_la_OBJECTS = $(am__objects_2) \
	$(am__objects_4) arvenumtypes.lo
libaravis_0.6_la_OBJECTS =  \
	$(am_libaravis_0.6_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
PROGRAMS = $(bin_PROGRAMS)
am_arv_fake_gv_camera_0.6_OBJECTS =  \
	arvfakegvcamera.$(OBJEXT)
arv_fake_gv_camera_0.6_OBJECTS =  \
	$(am_arv_fake_gv_camera_0.6_OBJECTS)
arv_fake_gv_camera_0.6_DEPENDENCIES =  \
	$(am__DEPENDENCIES_1) libaravis-0.6.la
am_arv_test_0.6_OBJECTS = arvtest.$(OBJEXT)
arv_test_0.6_OBJECTS =  \
	$(am_arv_test_0.6_OBJECTS)
arv_test_0.6_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	libaravis-0.6.la
am_arv_tool_0.6_OBJECTS = arvtool.$(OBJEXT)
arv_tool_0.6_OBJECTS =  \
	$(am_arv_tool_0.6_OBJECTS)
arv_tool_0.6_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	libaravis-0.6.la
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libaravis_0.6_la_SOURCES) \
	$(arv_fake_gv_camera_0.6_SOURCES) \
	$(arv_test_0.6_SOURCES) \
	$(arv_tool_0.6_SOURCES)
DIST_SOURCES = $(am__libaravis_0.6_la_SOURCES_DIST) \
	$(arv_fake_gv_camera_0.6_SOURCES) \
	$(arv_test_0.6_SOURCES) \
	$(arv_tool_0.6_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(arv_fake_camera_DATA) $(gir_DATA) $(typelib_DATA)
am__libaravis_0.6_la_HEADERS_DIST = arv.h arvtypes.h \
	arvenums.h arvdebug.h arvsystem.h arvevaluator.h arvdomnode.h \
	arvdomnodelist.h arvdomnamednodemap.h arvdomdocument.h \
	arvdomdocumentfragment.h arvdomelement.h arvdomcharacterdata.h \
	arvdomtext.h arvdomparser.h arvdomimplementation.h arvcamera.h \
	arvgc.h arvgcnode.h arvgcpropertynode.h arvgcindexnode.h \
	arvgcvalueindexednode.h arvgcinvalidatornode.h \
	arvgcfeaturenode.h arvgcregisterdescriptionnode.h \
	arvgcgroupnode.h arvgccategory.h arvgcboolean.h \
	arvgcenumeration.h arvgcenumentry.h arvgcintegernode.h \
	arvgcfloatnode.h arvgcregisternode.h arvgcstructentrynode.h \
	arvgccommand.h arvgcswissknife.h arvgcconverter.h arvgcport.h \
	arvgcregister.h arvgcinteger.h arvgcstring.h arvgcfloat.h \
	arvinterface.h arvdevice.h arvstream.h arvbuffer.h \
	arvchunkparser.h arvgvinterface.h arvgvdevice.h arvgvstream.h \
	arvfakeinterface.h arvfakedevice.h arvfakestream.h \
	arvfakecamera.h arvgvfakecamera.h arvrealtime.h arvxmlschema.h \
	arvuvinterface.h arvuvdevice.h arvuvstream.h arvmisc.h \
	arvzip.h arvstr.h arvgvcp.h arvgvsp.h arvuvcp.h arvuvsp.h \
	arvenumtypes.h
HEADERS = $(libaravis_0.6_la_HEADERS) \
	$(nodist_libaravis_0.6_la_HEADERS) \
	$(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)arvconfig.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/arvconfig.h.in \
	$(srcdir)/arvfeatures.h.in $(srcdir)/arvversion.h.in \
	$(top_srcdir)/Makefile.decl $(top_srcdir)/depcomp
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/pi/arv/aravis/missing aclocal-1.15
ALL_LINGUAS = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
APPSTREAM_UTIL = 
AR = ar
ARAVIS_API_VERSION = 0.6
ARAVIS_API_VERSION_U = 0_6
ARAVIS_CFLAGS = -pthread -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include
ARAVIS_GST_0_10_PLUGIN_CFLAGS = 
ARAVIS_GST_0_10_PLUGIN_LIBS = -lm 
ARAVIS_GST_PLUGIN_CFLAGS = -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include
ARAVIS_GST_PLUGIN_LIBS = -lm -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
ARAVIS_HAS_PACKET_SOCKET = 0
ARAVIS_HAS_USB = 0
ARAVIS_LIBS = -lm -lgio-2.0 -lgobject-2.0 -lxml2 -lgthread-2.0 -pthread -lglib-2.0 -lz
ARAVIS_MAJOR_VERSION = 0
ARAVIS_MICRO_VERSION = 14
ARAVIS_MINOR_VERSION = 5
ARAVIS_PACKET_SOCKET_CFLAGS = 
ARAVIS_PACKET_SOCKET_LIBS = 
ARAVIS_USB_CFLAGS = 
ARAVIS_USB_LIBS = 
ARAVIS_VERSION = 0.5.14
ARAVIS_VIEWER_CFLAGS = -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include
ARAVIS_VIEWER_LIBS = -lm -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
AUTOCONF = ${SHELL} /home/pi/arv/aravis/missing autoconf
AUTOHEADER = ${SHELL} /home/pi/arv/aravis/missing autoheader
AUTOMAKE = ${SHELL} /home/pi/arv/aravis/missing automake-1.15
AWK = mawk
CATALOGS = 
CATOBJEXT = .gmo
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CODE_COVERAGE_CFLAGS = 
CODE_COVERAGE_CPPFLAGS = 
CODE_COVERAGE_CXXFLAGS = 
CODE_COVERAGE_ENABLED = no
CODE_COVERAGE_LDFLAGS = 
CODE_COVERAGE_LIBS = 
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DATADIRNAME = share
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENABLE_VALGRIND_drd = no
ENABLE_VALGRIND_helgrind = no
ENABLE_VALGRIND_memcheck = no
ENABLE_VALGRIND_sgcheck = no
EXEEXT = 
FGREP = /bin/grep -F
GCOV = 
GENHTML = 
GETTEXT_PACKAGE = aravis-0.6
GLIB_MKENUMS = /usr/bin/glib-mkenums
GMOFILES = 
GMSGFMT = /usr/bin/msgfmt
GREP = /bin/grep
GST_0_10_PLUGIN_LDFLAGS = -module -avoid-version -export-symbols-regex _*\(gst_\|Gst\|GST_\).*
GST_PLUGIN_LDFLAGS = -module -avoid-version -export-symbols-regex _*\(gst_\|Gst\|GST_\).*
GTKDOC_CHECK = gtkdoc-check.test
GTKDOC_CHECK_PATH = /usr/bin/gtkdoc-check
GTKDOC_DEPS_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include
GTKDOC_DEPS_LIBS = -lgobject-2.0 -lglib-2.0
GTKDOC_MKPDF = /usr/bin/gtkdoc-mkpdf
GTKDOC_REBASE = /usr/bin/gtkdoc-rebase
HTML_DIR = ${datadir}/gtk-doc/html
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INSTOBJEXT = .mo
INTLLIBS = 
INTLTOOL_EXTRACT = /usr/bin/intltool-extract
INTLTOOL_MERGE = /usr/bin/intltool-merge
INTLTOOL_PERL = /usr/bin/perl
INTLTOOL_UPDATE = /usr/bin/intltool-update
INTLTOOL_V_MERGE = $(INTLTOOL__v_MERGE_$(V))
INTLTOOL_V_MERGE_OPTIONS = $(intltool__v_merge_options_$(V))
INTLTOOL__v_MERGE_ = $(INTLTOOL__v_MERGE_$(AM_DEFAULT_VERBOSITY))
INTLTOOL__v_MERGE_0 = @echo "  ITMRG " $@;
INTL_MACOSX_LIBS = 
INTROSPECTION_CFLAGS = -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include
INTROSPECTION_COMPILER = /usr/bin/g-ir-compiler
INTROSPECTION_GENERATE = /usr/bin/g-ir-generate
INTROSPECTION_GIRDIR = /usr/share/gir-1.0
INTROSPECTION_LIBS = -lgirepository-1.0 -lgobject-2.0 -lglib-2.0
INTROSPECTION_MAKEFILE = /usr/share/gobject-introspection-1.0/Makefile.introspection
INTROSPECTION_SCANNER = /usr/bin/g-ir-scanner
INTROSPECTION_TYPELIBDIR = /usr/lib/arm-linux-gnueabihf/girepository-1.0
LCOV = 
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAINT = #
MAKEINFO = ${SHELL} /home/pi/arv/aravis/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
MKINSTALLDIRS = ./mkinstalldirs
MSGFMT = /usr/bin/msgfmt
MSGFMT_OPTS = -c
MSGMERGE = /usr/bin/msgmerge
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = aravis
PACKAGE_BUGREPORT = http://bugzilla.gnome.org/enter_bug.cgi?product=aravis
PACKAGE_NAME = aravis
PACKAGE_STRING = aravis 0.5.14
PACKAGE_TARNAME = aravis
PACKAGE_URL = 
PACKAGE_VERSION = 0.5.14
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
POFILES = 
POSUB = po
PO_IN_DATADIR_FALSE = 
PO_IN_DATADIR_TRUE = 
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
USE_NLS = yes
VALGRIND = 
VALGRIND_ENABLED = no
VERSION = 0.5.14
XGETTEXT = /usr/bin/xgettext
abs_builddir = /home/pi/arv/aravis/src
abs_srcdir = /home/pi/arv/aravis/src
abs_top_builddir = /home/pi/arv/aravis
abs_top_srcdir = /home/pi/arv/aravis
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
appstreamxmldir = ${datarootdir}/appdata
aravis_datadir = $(datadir)/aravis-$(ARAVIS_API_VERSION)
bindir = ${exec_prefix}/bin
build = armv7l-unknown-linux-gnueabihf
build_alias = 
build_cpu = armv7l
build_os = linux-gnueabihf
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gst010plugindir = $(libdir)/gstreamer-0.10
gstplugindir = $(libdir)/gstreamer-1.0
host = armv7l-unknown-linux-gnueabihf
host_alias = 
host_cpu = armv7l
host_os = linux-gnueabihf
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/pi/arv/aravis/install-sh
intltool__v_merge_options_ = $(intltool__v_merge_options_$(AM_DEFAULT_VERBOSITY))
intltool__v_merge_options_0 = -q
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
valgrind_enabled_tools = 
valgrind_tools = memcheck helgrind drd sgcheck
EXTRA_DIST = arvenumtypes.h.template arvenumtypes.c.template \
	arv-fake-camera.xml
GTESTER = gtester
GTESTER_REPORT = gtester-report

# initialize variables for unconditional += appending
TEST_PROGS = 
AM_CPPFLAGS = \
	-DPACKAGE_LOCALE_DIR=\""$(prefix)/$(DATADIRNAME)/locale"\" 	\
	-DPACKAGE_SRC_DIR=\""$(srcdir)"\" 				\
	-DPACKAGE_DATA_DIR=\""$(datadir)"\" $(ARAVIS_CFLAGS) 		\
	-DARAVIS_DATA_DIR=\""$(aravis_datadir)"\" 			\
	-DARAVIS_API_VERSION=\""$(ARAVIS_API_VERSION)"\" 		\
	-DG_LOG_DOMAIN=\"Aravis\"					\
	-DARAVIS_COMPILATION

AM_CFLAGS = -Wall $(CODE_COVERAGE_CFLAGS)
lib_LTLIBRARIES = libaravis-0.6.la
BUILT_SOURCES = arvenumtypes.h arvenumtypes.c arvfeatures.h arvversion.h
libaravis_0.6_la_LIBADD = \
	$(ARAVIS_LIBS) $(CODE_COVERAGE_LIBS)

ARAVIS_SRCS = arvenums.c arvdebug.c arvsystem.c arvevaluator.c \
	arvdomnode.c arvdomnodelist.c arvdomnamednodemap.c \
	arvdomdocument.c arvdomdocumentfragment.c arvdomelement.c \
	arvdomcharacterdata.c arvdomtext.c arvdomparser.c \
	arvdomimplementation.c arvcamera.c arvgc.c arvgcnode.c \
	arvgcpropertynode.c arvgcindexnode.c arvgcvalueindexednode.c \
	arvgcinvalidatornode.c arvgcfeaturenode.c \
	arvgcregisterdescriptionnode.c arvgcgroupnode.c \
	arvgccategory.c arvgcboolean.c arvgcenumeration.c \
	arvgcenumentry.c arvgcintegernode.c arvgcfloatnode.c \
	arvgcregisternode.c arvgcstructentrynode.c arvgccommand.c \
	arvgcswissknife.c arvgcconverter.c arvgcport.c arvgcregister.c \
	arvgcinteger.c arvgcstring.c arvgcfloat.c arvinterface.c \
	arvdevice.c arvstream.c arvbuffer.c arvchunkparser.c \
	arvgvinterface.c arvgvdevice.c arvgvstream.c \
	arvfakeinterface.c arvfakedevice.c arvfakestream.c \
	arvfakecamera.c arvgvfakecamera.c arvrealtime.c arvxmlschema.c \
	$(am__append_1)
ARAVIS_SRCS_NO_INTRO = arvmisc.c arvzip.c arvstr.c arvgvcp.c arvgvsp.c \
	$(am__append_2)
ARAVIS_HDRS = arv.h arvtypes.h arvenums.h arvdebug.h arvsystem.h \
	arvevaluator.h arvdomnode.h arvdomnodelist.h \
	arvdomnamednodemap.h arvdomdocument.h arvdomdocumentfragment.h \
	arvdomelement.h arvdomcharacterdata.h arvdomtext.h \
	arvdomparser.h arvdomimplementation.h arvcamera.h arvgc.h \
	arvgcnode.h arvgcpropertynode.h arvgcindexnode.h \
	arvgcvalueindexednode.h arvgcinvalidatornode.h \
	arvgcfeaturenode.h arvgcregisterdescriptionnode.h \
	arvgcgroupnode.h arvgccategory.h arvgcboolean.h \
	arvgcenumeration.h arvgcenumentry.h arvgcintegernode.h \
	arvgcfloatnode.h arvgcregisternode.h arvgcstructentrynode.h \
	arvgccommand.h arvgcswissknife.h arvgcconverter.h arvgcport.h \
	arvgcregister.h arvgcinteger.h arvgcstring.h arvgcfloat.h \
	arvinterface.h arvdevice.h arvstream.h arvbuffer.h \
	arvchunkparser.h arvgvinterface.h arvgvdevice.h arvgvstream.h \
	arvfakeinterface.h arvfakedevice.h arvfakestream.h \
	arvfakecamera.h arvgvfakecamera.h arvrealtime.h arvxmlschema.h \
	$(am__append_3)
ARAVIS_HDRS_NO_INTRO = arvmisc.h arvzip.h arvstr.h arvgvcp.h arvgvsp.h \
	$(am__append_4)
noinst_HEADERS = \
	arvbufferprivate.h			\
	arvchunkparserprivate.h			\
	arvinterfaceprivate.h			\
	arvdeviceprivate.h			\
	arvstreamprivate.h			\
	arvgvinterfaceprivate.h			\
	arvgvdeviceprivate.h			\
	arvgvstreamprivate.h			\
	arvuvinterfaceprivate.h			\
	arvuvdeviceprivate.h			\
	arvuvstreamprivate.h			\
	arvfakeinterfaceprivate.h		\
	arvfakedeviceprivate.h			\
	arvfakestreamprivate.h			\
	arvrealtimeprivate.h

arv_fake_cameradir = $(aravis_datadir)
arv_fake_camera_DATA = arv-fake-camera.xml
libaravis_0.6_la_SOURCES = $(ARAVIS_SRCS) \
	$(ARAVIS_SRCS_NO_INTRO) arvenumtypes.c
libaravis_0.6_ladir = $(includedir)/aravis-0.6
libaravis_0.6_la_HEADERS = $(ARAVIS_HDRS) \
	$(ARAVIS_HDRS_NO_INTRO) arvenumtypes.h
nodist_libaravis_0.6_la_HEADERS = arvfeatures.h arvversion.h
arv_fake_gv_camera_0.6_SOURCES = arvfakegvcamera.c
arv_fake_gv_camera_0.6_LDADD = $(ARAVIS_LIBS) libaravis-0.6.la
arv_tool_0.6_SOURCES = arvtool.c
arv_tool_0.6_LDADD = $(ARAVIS_LIBS) libaravis-0.6.la
arv_test_0.6_SOURCES = arvtest.c
arv_test_0.6_LDADD = $(ARAVIS_LIBS) libaravis-0.6.la
CLEANFILES = $(BUILT_SOURCES) $(am__append_6)
INTROSPECTION_GIRS = $(am__append_5)
INTROSPECTION_SCANNER_ARGS = --add-include-path=$(srcdir)
INTROSPECTION_COMPILER_ARGS = --includedir=$(srcdir)
introspection_files = $(ARAVIS_SRCS) \
		      $(ARAVIS_HDRS)

introspection_generated_files = \
		      arvenumtypes.c \
		      arvenumtypes.h

Aravis_0_6_gir_INCLUDES = GObject-2.0 Gio-2.0
Aravis_0_6_gir_SCANNERFLAGS = --identifier-prefix=Arv --warn-all
Aravis_0_6_gir_CFLAGS = $(INCLUDES) -I$(top_srcdir)/src -DARAVIS_COMPILATION
Aravis_0_6_gir_LIBS = libaravis-0.6.la
Aravis_0_6_gir_FILES = $(addprefix $(srcdir)/,$(introspection_files)) \
					  $(addprefix $(builddir)/,$(introspection_generated_files))

girdir = $(datadir)/gir-1.0
gir_DATA = $(INTROSPECTION_GIRS)
typelibdir = $(libdir)/girepository-1.0
typelib_DATA = $(INTROSPECTION_GIRS:.gir=.typelib)
all: $(BUILT_SOURCES) arvconfig.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am $(top_srcdir)/Makefile.decl $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;
$(top_srcdir)/Makefile.decl $(am__empty):

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure: # $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

arvconfig.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/arvconfig.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status src/arvconfig.h
$(srcdir)/arvconfig.h.in: # $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f arvconfig.h stamp-h1
arvfeatures.h: $(top_builddir)/config.status $(srcdir)/arvfeatures.h.in
	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
arvversion.h: $(top_builddir)/config.status $(srcdir)/arvversion.h.in
	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

libaravis-0.6.la: $(libaravis_0.6_la_OBJECTS) $(libaravis_0.6_la_DEPENDENCIES) $(EXTRA_libaravis_0.6_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(libaravis_0.6_la_OBJECTS) $(libaravis_0.6_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

arv-fake-gv-camera-0.6$(EXEEXT): $(arv_fake_gv_camera_0.6_OBJECTS) $(arv_fake_gv_camera_0.6_DEPENDENCIES) $(EXTRA_arv_fake_gv_camera_0.6_DEPENDENCIES) 
	@rm -f arv-fake-gv-camera-0.6$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(arv_fake_gv_camera_0.6_OBJECTS) $(arv_fake_gv_camera_0.6_LDADD) $(LIBS)

arv-test-0.6$(EXEEXT): $(arv_test_0.6_OBJECTS) $(arv_test_0.6_DEPENDENCIES) $(EXTRA_arv_test_0.6_DEPENDENCIES) 
	@rm -f arv-test-0.6$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(arv_test_0.6_OBJECTS) $(arv_test_0.6_LDADD) $(LIBS)

arv-tool-0.6$(EXEEXT): $(arv_tool_0.6_OBJECTS) $(arv_tool_0.6_DEPENDENCIES) $(EXTRA_arv_tool_0.6_DEPENDENCIES) 
	@rm -f arv-tool-0.6$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(arv_tool_0.6_OBJECTS) $(arv_tool_0.6_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/arvbuffer.Plo
include ./$(DEPDIR)/arvcamera.Plo
include ./$(DEPDIR)/arvchunkparser.Plo
include ./$(DEPDIR)/arvdebug.Plo
include ./$(DEPDIR)/arvdevice.Plo
include ./$(DEPDIR)/arvdomcharacterdata.Plo
include ./$(DEPDIR)/arvdomdocument.Plo
include ./$(DEPDIR)/arvdomdocumentfragment.Plo
include ./$(DEPDIR)/arvdomelement.Plo
include ./$(DEPDIR)/arvdomimplementation.Plo
include ./$(DEPDIR)/arvdomnamednodemap.Plo
include ./$(DEPDIR)/arvdomnode.Plo
include ./$(DEPDIR)/arvdomnodelist.Plo
include ./$(DEPDIR)/arvdomparser.Plo
include ./$(DEPDIR)/arvdomtext.Plo
include ./$(DEPDIR)/arvenums.Plo
include ./$(DEPDIR)/arvenumtypes.Plo
include ./$(DEPDIR)/arvevaluator.Plo
include ./$(DEPDIR)/arvfakecamera.Plo
include ./$(DEPDIR)/arvfakedevice.Plo
include ./$(DEPDIR)/arvfakegvcamera.Po
include ./$(DEPDIR)/arvfakeinterface.Plo
include ./$(DEPDIR)/arvfakestream.Plo
include ./$(DEPDIR)/arvgc.Plo
include ./$(DEPDIR)/arvgcboolean.Plo
include ./$(DEPDIR)/arvgccategory.Plo
include ./$(DEPDIR)/arvgccommand.Plo
include ./$(DEPDIR)/arvgcconverter.Plo
include ./$(DEPDIR)/arvgcenumentry.Plo
include ./$(DEPDIR)/arvgcenumeration.Plo
include ./$(DEPDIR)/arvgcfeaturenode.Plo
include ./$(DEPDIR)/arvgcfloat.Plo
include ./$(DEPDIR)/arvgcfloatnode.Plo
include ./$(DEPDIR)/arvgcgroupnode.Plo
include ./$(DEPDIR)/arvgcindexnode.Plo
include ./$(DEPDIR)/arvgcinteger.Plo
include ./$(DEPDIR)/arvgcintegernode.Plo
include ./$(DEPDIR)/arvgcinvalidatornode.Plo
include ./$(DEPDIR)/arvgcnode.Plo
include ./$(DEPDIR)/arvgcport.Plo
include ./$(DEPDIR)/arvgcpropertynode.Plo
include ./$(DEPDIR)/arvgcregister.Plo
include ./$(DEPDIR)/arvgcregisterdescriptionnode.Plo
include ./$(DEPDIR)/arvgcregisternode.Plo
include ./$(DEPDIR)/arvgcstring.Plo
include ./$(DEPDIR)/arvgcstructentrynode.Plo
include ./$(DEPDIR)/arvgcswissknife.Plo
include ./$(DEPDIR)/arvgcvalueindexednode.Plo
include ./$(DEPDIR)/arvgvcp.Plo
include ./$(DEPDIR)/arvgvdevice.Plo
include ./$(DEPDIR)/arvgvfakecamera.Plo
include ./$(DEPDIR)/arvgvinterface.Plo
include ./$(DEPDIR)/arvgvsp.Plo
include ./$(DEPDIR)/arvgvstream.Plo
include ./$(DEPDIR)/arvinterface.Plo
include ./$(DEPDIR)/arvmisc.Plo
include ./$(DEPDIR)/arvrealtime.Plo
include ./$(DEPDIR)/arvstr.Plo
include ./$(DEPDIR)/arvstream.Plo
include ./$(DEPDIR)/arvsystem.Plo
include ./$(DEPDIR)/arvtest.Po
include ./$(DEPDIR)/arvtool.Po
include ./$(DEPDIR)/arvuvcp.Plo
include ./$(DEPDIR)/arvuvdevice.Plo
include ./$(DEPDIR)/arvuvinterface.Plo
include ./$(DEPDIR)/arvuvsp.Plo
include ./$(DEPDIR)/arvuvstream.Plo
include ./$(DEPDIR)/arvxmlschema.Plo
include ./$(DEPDIR)/arvzip.Plo

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
install-arv_fake_cameraDATA: $(arv_fake_camera_DATA)
	@$(NORMAL_INSTALL)
	@list='$(arv_fake_camera_DATA)'; test -n "$(arv_fake_cameradir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(arv_fake_cameradir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(arv_fake_cameradir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(arv_fake_cameradir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(arv_fake_cameradir)" || exit $$?; \
	done

uninstall-arv_fake_cameraDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(arv_fake_camera_DATA)'; test -n "$(arv_fake_cameradir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(arv_fake_cameradir)'; $(am__uninstall_files_from_dir)
install-girDATA: $(gir_DATA)
	@$(NORMAL_INSTALL)
	@list='$(gir_DATA)'; test -n "$(girdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(girdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(girdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(girdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(girdir)" || exit $$?; \
	done

uninstall-girDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(gir_DATA)'; test -n "$(girdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(girdir)'; $(am__uninstall_files_from_dir)
install-typelibDATA: $(typelib_DATA)
	@$(NORMAL_INSTALL)
	@list='$(typelib_DATA)'; test -n "$(typelibdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(typelibdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(typelibdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(typelibdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(typelibdir)" || exit $$?; \
	done

uninstall-typelibDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(typelib_DATA)'; test -n "$(typelibdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(typelibdir)'; $(am__uninstall_files_from_dir)
install-libaravis_0.6_laHEADERS: $(libaravis_0.6_la_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(libaravis_0.6_la_HEADERS)'; test -n "$(libaravis_0.6_ladir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libaravis_0.6_ladir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libaravis_0.6_ladir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(libaravis_0.6_ladir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(libaravis_0.6_ladir)" || exit $$?; \
	done

uninstall-libaravis_0.6_laHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(libaravis_0.6_la_HEADERS)'; test -n "$(libaravis_0.6_ladir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(libaravis_0.6_ladir)'; $(am__uninstall_files_from_dir)
install-nodist_libaravis_0.6_laHEADERS: $(nodist_libaravis_0.6_la_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nodist_libaravis_0.6_la_HEADERS)'; test -n "$(libaravis_0.6_ladir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libaravis_0.6_ladir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libaravis_0.6_ladir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(libaravis_0.6_ladir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(libaravis_0.6_ladir)" || exit $$?; \
	done

uninstall-nodist_libaravis_0.6_laHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nodist_libaravis_0.6_la_HEADERS)'; test -n "$(libaravis_0.6_ladir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(libaravis_0.6_ladir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-local
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS) \
		arvconfig.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(arv_fake_cameradir)" "$(DESTDIR)$(girdir)" "$(DESTDIR)$(typelibdir)" "$(DESTDIR)$(libaravis_0.6_ladir)" "$(DESTDIR)$(libaravis_0.6_ladir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-arv_fake_cameraDATA install-girDATA \
	install-libaravis_0.6_laHEADERS \
	install-nodist_libaravis_0.6_laHEADERS \
	install-typelibDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-arv_fake_cameraDATA uninstall-binPROGRAMS \
	uninstall-girDATA uninstall-libLTLIBRARIES \
	uninstall-libaravis_0.6_laHEADERS \
	uninstall-nodist_libaravis_0.6_laHEADERS \
	uninstall-typelibDATA

.MAKE: all check check-am install install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am check check-am check-local clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool cscopelist-am ctags ctags-am distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am \
	install-arv_fake_cameraDATA install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-girDATA install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-libaravis_0.6_laHEADERS install-man \
	install-nodist_libaravis_0.6_laHEADERS \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip install-typelibDATA installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-arv_fake_cameraDATA \
	uninstall-binPROGRAMS uninstall-girDATA \
	uninstall-libLTLIBRARIES \
	uninstall-libaravis_0.6_laHEADERS \
	uninstall-nodist_libaravis_0.6_laHEADERS \
	uninstall-typelibDATA

.PRECIOUS: Makefile


### testing rules

# test: run all tests in cwd and subdirs
test:	${TEST_PROGS}
	@test -z "${TEST_PROGS}" || ${GTESTER} --verbose ${TEST_PROGS}
	@ for subdir in $(SUBDIRS) . ; do \
	    test "$$subdir" = "." -o "$$subdir" = "po" || \
	    ( cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $@ ) || exit $? ; \
	  done

# test-report: run tests in subdirs and generate report
# perf-report: run tests in subdirs with -m perf and generate report
# full-report: like test-report: with -m perf and -m slow
test-report perf-report full-report:	${TEST_PROGS}
	@test -z "${TEST_PROGS}" || { \
	  case $@ in \
	  test-report) test_options="-k";; \
	  perf-report) test_options="-k -m=perf";; \
	  full-report) test_options="-k -m=perf -m=slow";; \
	  esac ; \
	  if test -z "$$GTESTER_LOGDIR" ; then	\
	    ${GTESTER} --verbose $$test_options -o test-report.xml ${TEST_PROGS} ; \
	  elif test -n "${TEST_PROGS}" ; then \
	    ${GTESTER} --verbose $$test_options -o `mktemp "$$GTESTER_LOGDIR/log-XXXXXX"` ${TEST_PROGS} ; \
	  fi ; \
	}
	@ ignore_logdir=true ; \
	  if test -z "$$GTESTER_LOGDIR" ; then \
	    GTESTER_LOGDIR=`mktemp -d "\`pwd\`/.testlogs-XXXXXX"`; export GTESTER_LOGDIR ; \
	    ignore_logdir=false ; \
	  fi ; \
	  for subdir in $(SUBDIRS) . ; do \
	    test "$$subdir" = "." -o "$$subdir" = "po" || \
	    ( cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $@ ) || exit $? ; \
	  done ; \
	  $$ignore_logdir || { \
	    echo '<?xml version="1.0"?>' > $@.xml ; \
	    echo '<report-collection>'  >> $@.xml ; \
	    for lf in `ls -L "$$GTESTER_LOGDIR"/.` ; do \
	      sed '1,1s/^<?xml\b[^>?]*?>//' <"$$GTESTER_LOGDIR"/"$$lf" >> $@.xml ; \
	    done ; \
	    echo >> $@.xml ; \
	    echo '</report-collection>' >> $@.xml ; \
	    rm -rf "$$GTESTER_LOGDIR"/ ; \
	    ${GTESTER_REPORT} --version 2>/dev/null 1>&2 ; test "$$?" != 0 || ${GTESTER_REPORT} $@.xml >$@.html ; \
	  }
.PHONY: test test-report perf-report full-report
# run make test as part of make check
check-local: test


# Code coverage
#
# Optional:
#  - CODE_COVERAGE_DIRECTORY: Top-level directory for code coverage reporting.
#    Multiple directories may be specified, separated by whitespace.
#    (Default: $(top_builddir))
#  - CODE_COVERAGE_OUTPUT_FILE: Filename and path for the .info file generated
#    by lcov for code coverage. (Default:
#    $(PACKAGE_NAME)-$(PACKAGE_VERSION)-coverage.info)
#  - CODE_COVERAGE_OUTPUT_DIRECTORY: Directory for generated code coverage
#    reports to be created. (Default:
#    $(PACKAGE_NAME)-$(PACKAGE_VERSION)-coverage)
#  - CODE_COVERAGE_BRANCH_COVERAGE: Set to 1 to enforce branch coverage,
#    set to 0 to disable it and leave empty to stay with the default.
#    (Default: empty)
#  - CODE_COVERAGE_LCOV_SHOPTS_DEFAULT: Extra options shared between both lcov
#    instances. (Default: based on $CODE_COVERAGE_BRANCH_COVERAGE)
#  - CODE_COVERAGE_LCOV_SHOPTS: Extra options to shared between both lcov
#    instances. (Default: $CODE_COVERAGE_LCOV_SHOPTS_DEFAULT)
#  - CODE_COVERAGE_LCOV_OPTIONS_GCOVPATH: --gcov-tool pathtogcov
#  - CODE_COVERAGE_LCOV_OPTIONS_DEFAULT: Extra options to pass to the
#    collecting lcov instance. (Default: $CODE_COVERAGE_LCOV_OPTIONS_GCOVPATH)
#  - CODE_COVERAGE_LCOV_OPTIONS: Extra options to pass to the collecting lcov
#    instance. (Default: $CODE_COVERAGE_LCOV_OPTIONS_DEFAULT)
#  - CODE_COVERAGE_LCOV_RMOPTS_DEFAULT: Extra options to pass to the filtering
#    lcov instance. (Default: empty)
#  - CODE_COVERAGE_LCOV_RMOPTS: Extra options to pass to the filtering lcov
#    instance. (Default: $CODE_COVERAGE_LCOV_RMOPTS_DEFAULT)
#  - CODE_COVERAGE_GENHTML_OPTIONS_DEFAULT: Extra options to pass to the
#    genhtml instance. (Default: based on $CODE_COVERAGE_BRANCH_COVERAGE)
#  - CODE_COVERAGE_GENHTML_OPTIONS: Extra options to pass to the genhtml
#    instance. (Default: $CODE_COVERAGE_GENHTML_OPTIONS_DEFAULT)
#  - CODE_COVERAGE_IGNORE_PATTERN: Extra glob pattern of files to ignore
#
# The generated report will be titled using the $(PACKAGE_NAME) and
# $(PACKAGE_VERSION). In order to add the current git hash to the title,
# use the git-version-gen script, available online.

# Optional variables
CODE_COVERAGE_DIRECTORY ?= $(top_builddir)
CODE_COVERAGE_OUTPUT_FILE ?= $(PACKAGE_NAME)-$(PACKAGE_VERSION)-coverage.info
CODE_COVERAGE_OUTPUT_DIRECTORY ?= $(PACKAGE_NAME)-$(PACKAGE_VERSION)-coverage
CODE_COVERAGE_BRANCH_COVERAGE ?=
CODE_COVERAGE_LCOV_SHOPTS_DEFAULT ?= $(if $(CODE_COVERAGE_BRANCH_COVERAGE),\
--rc lcov_branch_coverage=$(CODE_COVERAGE_BRANCH_COVERAGE))
CODE_COVERAGE_LCOV_SHOPTS ?= $(CODE_COVERAGE_LCOV_SHOPTS_DEFAULT)
CODE_COVERAGE_LCOV_OPTIONS_GCOVPATH ?= --gcov-tool "$(GCOV)"
CODE_COVERAGE_LCOV_OPTIONS_DEFAULT ?= $(CODE_COVERAGE_LCOV_OPTIONS_GCOVPATH)
CODE_COVERAGE_LCOV_OPTIONS ?= $(CODE_COVERAGE_LCOV_OPTIONS_DEFAULT)
CODE_COVERAGE_LCOV_RMOPTS_DEFAULT ?=
CODE_COVERAGE_LCOV_RMOPTS ?= $(CODE_COVERAGE_LCOV_RMOPTS_DEFAULT)
CODE_COVERAGE_GENHTML_OPTIONS_DEFAULT ?=\
$(if $(CODE_COVERAGE_BRANCH_COVERAGE),\
--rc genhtml_branch_coverage=$(CODE_COVERAGE_BRANCH_COVERAGE))
CODE_COVERAGE_GENHTML_OPTIONS ?= $(CODE_COVERAGE_GENHTML_OPTIONS_DEFAULTS)
CODE_COVERAGE_IGNORE_PATTERN ?=

code_coverage_v_lcov_cap = $(code_coverage_v_lcov_cap_$(V))
code_coverage_v_lcov_cap_ = $(code_coverage_v_lcov_cap_$(AM_DEFAULT_VERBOSITY))
code_coverage_v_lcov_cap_0 = @echo "  LCOV   --capture"\
 $(CODE_COVERAGE_OUTPUT_FILE);
code_coverage_v_lcov_ign = $(code_coverage_v_lcov_ign_$(V))
code_coverage_v_lcov_ign_ = $(code_coverage_v_lcov_ign_$(AM_DEFAULT_VERBOSITY))
code_coverage_v_lcov_ign_0 = @echo "  LCOV   --remove /tmp/*"\
 $(CODE_COVERAGE_IGNORE_PATTERN);
code_coverage_v_genhtml = $(code_coverage_v_genhtml_$(V))
code_coverage_v_genhtml_ = $(code_coverage_v_genhtml_$(AM_DEFAULT_VERBOSITY))
code_coverage_v_genhtml_0 = @echo "  GEN   " $(CODE_COVERAGE_OUTPUT_DIRECTORY);
code_coverage_quiet = $(code_coverage_quiet_$(V))
code_coverage_quiet_ = $(code_coverage_quiet_$(AM_DEFAULT_VERBOSITY))
code_coverage_quiet_0 = --quiet

# sanitizes the test-name: replaces with underscores: dashes and dots
code_coverage_sanitize = $(subst -,_,$(subst .,_,$(1)))

# Use recursive makes in order to ignore errors during check
check-code-coverage:
	@echo "Need to reconfigure with --enable-code-coverage"


# Capture code coverage data
code-coverage-capture: code-coverage-capture-hook
	@echo "Need to reconfigure with --enable-code-coverage"


# Hook rule executed before code-coverage-capture, overridable by the user
code-coverage-capture-hook:



GITIGNOREFILES ?=
GITIGNOREFILES += $(CODE_COVERAGE_OUTPUT_FILE) $(CODE_COVERAGE_OUTPUT_DIRECTORY)

AM_DISTCHECK_CONFIGURE_FLAGS ?=
AM_DISTCHECK_CONFIGURE_FLAGS += --disable-code-coverage

.PHONY: check-code-coverage code-coverage-capture code-coverage-capture-hook code-coverage-clean


arvenumtypes.h: arvenumtypes.h.template $(ARAVIS_HDRS) $(ARAVIS_HDRS_NO_INTRO) $(GLIB_MKENUMS)
	$(AM_V_GEN) (cd $(srcdir) && $(GLIB_MKENUMS) --template arvenumtypes.h.template $(libaravis_0.6_la_HEADERS)) > $@

arvenumtypes.c: arvenumtypes.c.template $(ARAVIS_HDRS) $(ARAVIS_HDRS_NO_INTRO) $(GLIB_MKENUMS)
	$(AM_V_GEN) (cd $(srcdir) && $(GLIB_MKENUMS) --template arvenumtypes.c.template $(libaravis_0.6_la_HEADERS)) > $@

-include $(INTROSPECTION_MAKEFILE)

Aravis-0.6.gir: $(INTROSPECTION_SCANNER) libaravis-0.6.la Makefile

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
